export const ProductList = [
    { id: 1, name: "Nike Air Max 270 React",rating: 4, price: 100, OriginalPrice: 150,discount:24 ,image: "src/assets/img/shoes1.svg" , hot:"true", brand:"Nike", color:"Black"},
    { id: 2, name: "Nike Air Max 270 React",rating: 5, price: 200, OriginalPrice: 250,discount:20 ,image: "src/assets/img/brownBag.svg", hot:"true", brand:"Adidas",color:"Orange" },
    { id: 3, name: "Nike Air Max 270 React",rating: 3, price: 300, OriginalPrice: 350,discount:15 ,image: "src/assets/img/beigeBag.svg", hot:"true", brand:"Reebok",color:"Beige" },
    { id: 4, name: "Nike Air Max 270 React",rating: 4, price: 400, OriginalPrice: 450,discount:10 ,image: "src/assets/img/shoes2.svg", hot:"false", brand:"Puma",color:"Blue" },
    { id: 5, name: "Nike Air Max 270 React",rating: 2, price: 500, OriginalPrice: 550,discount:5 ,image: "src/assets/img/shoes3.svg", hot:"true", brand:"Skechers",color:"Yellow" },
    { id: 6, name: "Nike Air Max 270 React",rating: 5, price: 600, OriginalPrice: 650,discount:30 ,image: "src/assets/img/shoes4.svg", hot:"true", brand:"Airmax",color:"Pink" },
    { id: 7, name: "Nike Air Max 270 React",rating: 4, price: 700, OriginalPrice: 750,discount:12 ,image: "src/assets/img/shoes1.svg", hot:"false", brand:"Puma" ,color:"Beige" },
    { id: 8, name: "Nike Air Max 270 React",rating: 3, price: 800, OriginalPrice: 850,discount:18 ,image: "src/assets/img/brownBag.svg", hot:"true", brand:"Nike",color:"Orange" },
    { id: 9, name: "Nike Air Max 270 React",rating: 4, price: 900, OriginalPrice: 950,discount:22 ,image: "src/assets/img/beigeBag.svg", hot:"true", brand:"Airmax" ,color:"Blue" },
    { id: 10, name: "Nike Air Max 270 React",rating: 5, price: 1000, OriginalPrice: 1050,discount:25 ,image: "src/assets/img/shoes3.svg", hot:"false", brand:"Reebok" ,color:"Yellow" },
    { id: 11, name: "Nike Air Max 270 React",rating: 2, price: 1100, OriginalPrice: 1150,discount:8 ,image: "src/assets/img/shoes2.svg", hot:"true", brand:"Adidas" , color:"Black"},
    { id: 12, name: "Nike Air Max 270 React",rating: 4, price: 1200, OriginalPrice: 1250,discount:14 ,image: "src/assets/img/shoes4.svg", hot:"false", brand:"Skechers",color:"Orange" },
    { id: 13, name: "Nike Air Max 270 React",rating: 4, price: 100, OriginalPrice: 150,discount:24 ,image: "src/assets/img/shoes1.svg" , hot:"true", brand:"Nike",color:"Pink" },
    { id: 14, name: "Nike Air Max 270 React",rating: 5, price: 200, OriginalPrice: 250,discount:20 ,image: "src/assets/img/brownBag.svg", hot:"true", brand:"Adidas",color:"Blue" },
    { id: 15, name: "Nike Air Max 270 React",rating: 3, price: 300, OriginalPrice: 350,discount:15 ,image: "src/assets/img/beigeBag.svg", hot:"true", brand:"Reebok" ,color:"Beige" },
    { id: 16, name: "Nike Air Max 270 React",rating: 4, price: 400, OriginalPrice: 450,discount:10 ,image: "src/assets/img/shoes2.svg", hot:"false", brand:"Puma",color:"Yellow"  },
    { id: 17, name: "Nike Air Max 270 React",rating: 2, price: 500, OriginalPrice: 550,discount:5 ,image: "src/assets/img/shoes3.svg", hot:"true", brand:"Skechers" ,color:"Pink" },
    { id: 18, name: "Nike Air Max 270 React",rating: 5, price: 600, OriginalPrice: 650,discount:30 ,image: "src/assets/img/shoes4.svg", hot:"true", brand:"Airmax" , color:"Black"},
    { id: 19, name: "Nike Air Max 270 React",rating: 4, price: 700, OriginalPrice: 750,discount:12 ,image: "src/assets/img/shoes1.svg", hot:"false", brand:"Puma",color:"Orange" },
    { id: 20, name: "Nike Air Max 270 React",rating: 3, price: 800, OriginalPrice: 850,discount:18 ,image: "src/assets/img/brownBag.svg", hot:"true", brand:"Nike" , color:"Black"},
    { id: 21, name: "Nike Air Max 270 React",rating: 4, price: 900, OriginalPrice: 950,discount:22 ,image: "src/assets/img/beigeBag.svg", hot:"true", brand:"Airmax" ,color:"Beige" },
    { id: 22, name: "Nike Air Max 270 React",rating: 5, price: 1000, OriginalPrice: 1050,discount:25 ,image: "src/assets/img/shoes2.svg", hot:"false", brand:"Reebok" , color:"Black"},
    { id: 23, name: "Nike Air Max 270 React",rating: 2, price: 1100, OriginalPrice: 1150,discount:8 ,image: "src/assets/img/shoes3.svg", hot:"true", brand:"Adidas",color:"Pink"  },
    { id: 24, name: "Nike Air Max 270 React",rating: 4, price: 1200, OriginalPrice: 1250,discount:14 ,image: "src/assets/img/shoes4.svg", hot:"false", brand:"Skechers" , color:"Black"},
    { id: 25, name: "Nike Air Max 270 React",rating: 4, price: 900, OriginalPrice: 950,discount:22 ,image: "src/assets/img/beigeBag.svg", hot:"true", brand:"Airmax",color:"Yellow"  },
    { id: 26, name: "Nike Air Max 270 React",rating: 5, price: 1000, OriginalPrice: 1050,discount:25 ,image: "src/assets/img/shoes3.svg", hot:"false", brand:"Reebok" ,color:"Blue" },
    { id: 27, name: "Nike Air Max 270 React",rating: 2, price: 1100, OriginalPrice: 1150,discount:8 ,image: "src/assets/img/shoes2.svg", hot:"true", brand:"Adidas" ,color:"Beige" },
    { id: 28, name: "Nike Air Max 270 React",rating: 4, price: 1200, OriginalPrice: 1250,discount:14 ,image: "src/assets/img/shoes4.svg", hot:"false", brand:"Skechers",color:"Orange" },
    { id: 29, name: "Nike Air Max 270 React",rating: 4, price: 100, OriginalPrice: 150,discount:24 ,image: "src/assets/img/shoes1.svg" , hot:"true", brand:"Nike",color:"Blue" },
    { id: 30, name: "Nike Air Max 270 React",rating: 5, price: 200, OriginalPrice: 250,discount:20 ,image: "src/assets/img/brownBag.svg", hot:"true", brand:"Adidas" ,color:"Pink" },
    { id: 31, name: "Nike Air Max 270 React",rating: 3, price: 300, OriginalPrice: 350,discount:15 ,image: "src/assets/img/beigeBag.svg", hot:"true", brand:"Reebok",color:"Orange" },
    { id: 32, name: "Nike Air Max 270 React",rating: 4, price: 400, OriginalPrice: 450,discount:10 ,image: "src/assets/img/shoes2.svg", hot:"false", brand:"Puma" ,color:"Yellow" },
];